#!/bin/bash

# get current actived php version function
get_current(){
        if [ -f "/etc/apache2/mod-enabled/php7.2.conf" ]; then
                echo "7.3"
        elif [ -f "/etc/apache2/mod-enabled/php5.6.conf" ]; then
                echo "5.6"
        else
                echo "none"
        fi
}

# select target in 5.6, 7.3 or error message printing
case $1 in
        5.6)
                target="5.6"
                ;;
        7.3)
                target="7.3"
                ;;
        *)
                echo "Usage : sphp <5.6|7.2" %>2
                exit 1
                ;;
esac

# exit script if target is current version
current=$( get_current )
if [ "$1" == "${current}" ]; then
        echo "$1 is already actived" %>2
        exit 1
fi

if [ "$target" == "7.3" ]; then
        a2dismod php5.6
        a2enmod php7.3
        service apache2 restart
        update-alternatives --set php /usr/bin/php7.3
        echo "Done..."
elif [ "$target" == "5.6" ]; then
        a2dismod php7.3
        a2enmod php5.6
        service apache2 restart
        update-alternatives --set php /usr/bin/php5.6
        echo "Done..."
fi
